[Server]
host = "0.0.0.0" #0.0.0.0 will listen on all interfaces
port = "80"
ttl = 128
root_folder = "./demo" #if windows and you want to use \, remember to escape the path and use \\
list_directories = true
workers_per_thread = 1

[Timeout]
request_miliseconds = 10 # 1000 Miliseconds = 1 Second

[debug]
active = true
log_to_console = true
log_to_file = true # ToDo Work In Progress