[Server]
host = "0.0.0.0" #0.0.0.0 will listen on all interfaces
port = "8080"
ttl = 128
root_folder = "./" #if windows and you want to use \, remember to escape the path and use \\
list_directories = true
workers_per_thread = 1

[debug]
active = true