[Server]
host = "0.0.0.0" #0.0.0.0 will listen on all interfaces
port = "80"
ttl = 128
#if windows and you want to use "\", remember to escape the path and use "\\" or use "/" allways
root_folder = "./demo" 
list_directories = true
workers_per_thread = 1
index = [
          "index.html",
          "index.htm",
          "index"
         ]

[Timeout]
# 1000 Miliseconds = 1 Second
request_miliseconds = 10 

[debug]
active = true
error = true
warning = true
verbose = false
log_to_console = true
# ToDo Work In Progress
log_to_file = true 